apiVersion: v1
kind: Secret

metadata:
  name: employee-secret
  namespace: employee

type: Opaque

stringData:

  DB_USER: employee_user

  DB_PASSWORD: employee_password

  MYSQL_ROOT_PASSWORD: root_password
